# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.14.2]
        redis-version: [6.2.5]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - run: npm ci
    - name: Create .env file
      run: |
          touch .env
          echo KAKAO_ID=${{ secrets.KAKAO_ID }} >> .env
          echo KAKAO_CALLBACK=${{ secrets.KAKAO_CALLBACK }} >> .env
          echo ACCESSKEY=${{ secrets.ACCESSKEY }} >> .env
          echo REFRESHKEY=${{ secrets.REFRESHKEY }} >> .env
          echo SESSION_SECRET=${{ secrets.SESSION_SECRET }} >> .env
          echo COOKIE_SECRET=${{ secrets.COOKIE_SECRET }} >> .env
          echo DBID=${{ secrets.DBID }} >> .env
          echo DBPW=${{ secrets.DBPW }} >> .env
          echo MAIL_ID=${{ secrets.MAIL_ID }} >> .env
          echo MAIL_PW=${{ secrets.MAIL_PW }} >> .env
          echo ATOKENEXPIRE=${{ secrets.ATOKENEXPIRE }} >> .env
          echo RTOKENEXPIRE=${{ secrets.RTOKENEXPIRE }} >> .env
          cat .env
    - run: npm run build --if-present
    - run: npm test